[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tinybpe"
authors = [{ name = "E.T. Romani", email = "myneluca@gmail.com" }]
description = "This is an ultra-fast, lightweight and clean code implementation of the Byte Pair Encoding (BPE) algorithm."
dependencies = ["regex"]
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
dynamic = ["version"]
keywords = ["BPE", "Byte Pair Encoding", "LLM", "tokenizer"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Topic :: Text Processing :: Linguistic",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
homepage = "https://github.com/neluca/tinybpe"

[tool.setuptools.dynamic]
version = { attr = "tinybpe.__version__" }
