"""
This is a Python-C-Extension module that implements the core algorithm of BPE (Byte-Pair-Encoding).
"""

from __future__ import annotations

class Tokenizer:
    """This is a BPE tokenizer implemented in C ."""

    def __init__(self, merges: list[tuple[int, int]], special_tokens: dict[bytes, int] | None = None): ...
    @property
    def merges(self) -> list[tuple[int, int]]: ...
    @property
    def vocab(self) -> dict[int, bytes]: ...
    @property
    def n_vocab(self) -> int: ...
    def encode(self, text_bytes: bytes) -> list[int]: ...
    def decode(self, ids: list[int]) -> bytes: ...
    def cache_decode(self, token_id: int) -> bytes | None: ...
    def cache_clean(self) -> None: ...

class Trainer:
    """This is a BPE trainer implemented in C ."""

    def __init__(self, list_bytes: list[bytes | bytearray]): ...
    @property
    def n_merges(self) -> int: ...
    @property
    def merges(self) -> list[tuple[int, int]]: ...
    def step(self) -> tuple[tuple[int, int], int, int] | None:
        """:returns pair, rank, frequency."""

    ...

    def load_merges(self, merges: list[tuple[int, int]]) -> None: ...

class BytesRemap:
    """This is a bytes(0 - 255) remapper."""

    def __init__(self, _remap: list[int]): ...
    def __call__(self, _bytes: bytes) -> bytes: ...
